project:
  type: website
  output-dir: docs

# Meta
description-meta: "Website of Simone Romiti"
author-meta: "Dr. Simone Romiti"

website:
  title: "Simone Romiti"
  image: "./linkedin-profile_picture-2.png"
  description: "Quarto Academic Website Template adapted by Dr. Gang He"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About me
        menu:
          - text: Education ğŸ“š
            href: education.qmd             
          - text: Experience ğŸ§‘â€ğŸ’¼
            href: experience.qmd 
          - text: Skills âš’ï¸
            href: skills.qmd 
          - text: Mindset ğŸ“ˆ
            href: mindset.qmd 
          - text: News ğŸ“°
            href: posts.qmd#category=news
          - text: Contact ğŸ“§
            href: contact.qmd             
      - text: Academia
        menu:        
        - text: List of Publications ğŸ“ƒ
          href: publications.qmd
        - text: Presentations 
          href: posts.qmd#category=presentation                   
        # - text: Grants
        #   href: projects.qmd                                
        - text: Teaching ğŸ‘¨â€ğŸ«
          href: teaching.qmd
      - text: Software
        menu:        
        - text: Python libraries
          href: python_libs.qmd
        - text: C++ libraries
          href: cpp_libs.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/simone-romiti
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/simone-romiti/
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Simone Romiti](https://simone-romiti.github.io/) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/simone-romiti/simone-romiti.github.io
        target: _blank
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-6509-447X
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=B95wK7wAAAAJ&hl=en
      - text: "{{< ai inspire >}}"   # use academic icons, "" are needed, you also need to install the fontawesome extension
        href: https://inspirehep.net/authors/1755571
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  # reader-mode: true

  # draft-mode: unlinked
  
  repo-url: https://github.com/simone-romiti/simone-romiti.github.io
  # repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: https://simone-romiti.github.io/
  
  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    fontsize: 14pt
    # link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    # include-in-header: "files/includes/_academic.qmd"

